### ISSUE TITLE
Локинг баланса на счёте

### ISSUE THREAD

**Issue by dapi** [openbill-service/openbill-core#15]
Необходим механизм блокировки средств на счёте. Предлагаю такой подход:

1) Блокировка происходит через добавление записи в таблицу `openbill_locks`. Так-же как при добавлении записи в `openbill_transaction` выполняется триггер, который переносит указанную сумму с баланса счета в заблокированную сумму.
2) Убрать блокировку можно только добавив ещё одну запись в таблицу `openbill_locks` с отрицательным значением. При этом обязательно указывать lock_key - ключ с которым происходила блокировка средств.
3) Можно заблокировать на 1000$ и потом разблокировать частями;

Миграции:

```
CREATE TABLE OPENBILL_LOCKS (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  owner_id        UUID,
  username        character varying(255) not null,
  date            date default current_date not null,
  created_at      timestamp without time zone default current_timestamp,
  account_id uuid not null,
  amount_cents    numeric not null,,
  amount_currency character varying(8) not null,
  key             character varying(256) not null,
  details         text not null,
  meta            hstore not null default ''::hstore,
  lock_key   character varying(256) not null,
  foreign key (lock_key) REFERENCES OPENBILL_LOCKS (key) ON DELETE RESTRICT ON UPDATE RESTRICT
  foreign key (account_id) REFERENCES OPENBILL_ACCOUNTS (id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE UNIQUE INDEX index_locks_on_key ON OPENBILL_LOCKS USING btree (key);
CREATE INDEX index_locks_on_meta ON OPENBILL_LOCKS USING gin (meta);
```

в таблицу openbill_accounts добавляется поле `locked_cents numeric not null 0`

## Тесты

1. Можно заблокировать сумму на счете, после этого. amount_cents счета уменьшится на заблокированную сумму, locked_cents увеличится.
2. Нельзя заблокировать сумму больше чем на amount_cents.
3. Нельзя разблокировать сумму меньше чем в locked_cents.
4. Нельзя разблокировать сумму большую чем была заблокирована с указанным `lock_key`

**Comment by vivanov-bitzlato** [comment]
Предлагаю принять данный реквест, т.к. вопрос с защитой от одновременного изменения данных это отдельная большая задача, блокировок нет во всем проекте, не только здесь

По тестированию и внедрению этого функционала есть отдельная задача
https://github.com/openbill-service/openbill-core/issues/20
