### ISSUE TITLE
Неверное именование миграций - попытка №2 - неверное именовение R миграций

### ISSUE THREAD

**Issue by igork-bz** [openbill-service/openbill-core#48]
Спецификация
https://flywaydb.org/documentation/concepts/migrations#sql-based-migrations

Перевожу документацию, тезисно:

Повторяющиеся миграции (Repeatable migrations) именуются так:
`Префикс` + `Разделитель`  +  `Описание` + `Суффикс`

`Префикс` - это английская буква `R`
`Разделитель` - это два символа подчеркивания
`Описание` - произвольный текст, длинной не более 200 знаков
Суффикс - `.sql`

`R` миграции не имеют версии, так как в них не определяются отношения, а пишется лишь код доступа к данным. 

----

Моя личная рекомендация: придерживаться следующего формата `Описания`
`NNN_Тип_Имя`

где 
`NNN` - порядковый номер очередности в которой должны прогоняться эти миграции (например view может зависеть от  функции, тогда функция будет 001 а view будет 002)
`Тип`  - тип объекта -  fun / view / trg / и так далее
`Имя` - такое же имя как и имя у объекта БД который там описывается (например имя функции)

**Comment by dapi** [comment]
@vivanov-bitzlato что скажешь?
